# RSDKv5 Xbox Settings
[Game]
language=0
gameWindow=1
streamsDisabled=false
dataFile=Data.rsdk
devMenu=true
# time of last save (unix timestamp)
lastFTS=0

[Window]
fullScreen=true
exclusiveFS=true
vsync=true
windowScale=1
screenCount=1
refreshRate=60
fsWidth=1280
fsHeight=720
windowWidth=1280
windowHeight=720
pixWidth=424
pixHeight=240
maxPixWidth=424
shaderSupport=false
shaderID=0
dimTimer=120
dimLimit=0.50
bordered=false

[Audio]
soundFXVolume=100
bgmVolume=100
streamVolume=100

[Keyboard 1]
up=26
down=22
left=4
right=7
A=40
B=44
C=41
X=43
Y=42
Z=56
start=39
select=42

[Controller 1]
up=26
down=22
left=4
right=7
A=40
B=44
C=41
X=43
Y=42
Z=56
start=39
select=42
